### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by fsworld009** [NetCZ/vue-separate-files-webpack-loader#3]
Hi:
Thank you for creating this project.

It would be nice if you could include a license of your choice so that other people understand how they could use the project, thanks.

**Comment by NetCZ** [comment]
Hello @fsworld009,
licence is already included, see https://github.com/NetCZ/vue-separate-files-webpack-loader/blob/master/LICENSE.

**Comment by fsworld009** [comment]
ah ok, not sure why I didn't see it that day, sorry for that
