### ISSUE TITLE
paradigms mixture.

### ISSUE THREAD

**Issue by juanfernandoe** [NetCZ/vue-separate-files-webpack-loader#4]
Hi.

Is posible to mix single file component with some separate files components in the same webpack project?

those area my rules, but it's not working

            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    hotReload: true
                }
            },

            {
                //notice modified file test
                test: /\.vue\./,
                use: [
                    {
                        loader: 'vue-loader',
                        options: {
                            hotReload: true
                        }
                    },
                    {
                        loader: 'vue-separate-files-webpack-loader',
                        options: {
                            global: {
                                //all files will have these
                                attr: 'value'
                            },
                            sass: {
                                //only SASS files will have these
                                attr: 'value'
                            },
                            style: {
                                //only style files will have these
                                attr: 'value'
                            }
                        }
                    }
                ]
            },

I'm getting this error.

HomePage.vue is a single file component

And separate file.
Core/Login.vue.js
Core/Login.vue.html
Core/Login.vue.css

ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/components/HomePage.vue
Module not found: Error: Can't resolve '../Core/Login' in '/Volumes/CSData/Drive/www/_test/vue/tpl2/app/components'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/components/HomePage.vue 90:0-39
 @ ./app/components/HomePage.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/App.vue
 @ ./app/App.vue
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./app/main.js

**Comment by NetCZ** [comment]
Hi @juanfernandoe,
how are you importing `Login` in your `HomePage` component?
Are you using `import Login from 'Core/Login.vue'` (notice '.vue' in file name)?
